# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Zone.create([ { name: 'Almagro' }, { name: 'Balvanera' }, { name: 'Agronomía' }, { name: 'Barracas' }, { name: 'Belgrano' }, { name: 'Boedo' }, { name: 'Caballito' }, { name: 'Chacarita' }, { name: 'Coghlan' }, { name: 'Colegiales' }, { name: 'Constitución' }, { name: 'Flores' }, { name: 'Floresta' }, { name: 'La Boca' }, { name: 'La Paternal' }, { name: 'Liniers' }, { name: 'Mataderos' }, { name: 'Monte Castro' }, { name: 'Montserrat' }, { name: 'Nueva Pompeya' }, { name: 'Nuñez' }, { name: 'Palermo' }, { name: 'Parque Avellaneda' }, { name: 'Parque Chacabuco' }, { name: 'Parque Patricios' }, { name: 'Puerto Madero' }, { name: 'Recoleta' }, { name: 'Retiro' }, { name: 'Saavedra' }, { name: 'San Cristóbal' }, { name: 'San Nicolás' }, { name: 'San Telmo' }, { name: 'Vélez Sarsfield' }, { name: 'Versalles' }, { name: 'Villa Crespo' }, { name: 'Villa del Parque' }, { name: 'Villa Devoto' }, { name: 'Villa Luro' }, { name: 'Villa General Mitre' }, { name: 'Villa Lugano' }, { name: 'Villa Ortúzar' }, { name: 'Villa Pueyrredón' }, { name: 'Villa Real' }, { name: 'Villa Riachuelo' }, { name: 'Villa Santa Rita' }, { name: 'Villa Soldati' }, { name: 'Villa Urquiza' } ])

AvailableCharacteristic.create([
	{ title: 'Agua corriente', group: :services },
	{ title: 'Desagüe cloacal', group: :services },
	{ title: 'Teléfono', group: :services },
	{ title: 'Pavimento', group: :services },
	{ title: 'Video cable', group: :services },
	{ title: 'Internet', group: :services },
	{ title: 'Luz', group: :services },
	{ title: 'Gas natural', group: :services },
	{ title: 'Disposición', group: :extended, options: '["Frente", "Contrafrente", "Interno", "Lateral"]' },
	{ title: 'Tipo de portón', group: :extended, options: '["Corredizo", "Levadizo"]' },
	{ title: 'F.O.T.', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Etapa', group: :extended, options: '["En pozo", "En construcción", "Terminado"]' },
	{ title: 'Ofrece financiación', group: :extended },
	{ title: 'Orientación', group: :extended, options: '["N", "S", "E", "O", "NE", "NO", "SE", "SO"]' },
	{ title: 'Tipo techo', group: :extended, options: '["Chapa", "Losa", "Pizarra", "Teja"]' },
	{ title: 'Cantidad pisos en edificio', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Superficie del terreno (m2)', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Largo del terreno (mts)', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Frente del terreno (mts)', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Altura del techo (mts)', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Cantidad dormitorios', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Cantidad de pisos en edificio', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Departamentos por piso', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Uso comercial', group: :extended },
	{ title: 'Estado del edificio', group: :extended, options: '["Reciclado", "Excelente", "Muy bueno", "Bueno", "Regular", "A refaccionar"]' },
	{ title: 'Apto profesional', group: :extended },
	{ title: 'Tipo edificio', group: :extended, options: '["Entre medianeras", "Torre", "Tipo block", "Esquina", "Antiguo", "Inteligente", "Primera categoría", "Estándar"]' },
	{ title: 'Luminosidad', group: :extended, options: '["Muy luminoso", "Luminoso", "Poco luminoso"]' },
	{ title: 'Permite mascotas', group: :extended },
	{ title: 'Apto crédito', group: :extended },
	{ title: 'Estado del inmueble', group: :extended, options: '["Reciclado", "Excelente", "Muy bueno", "Bueno", "Regular", "A refaccionar"]' },
	{ title: 'Cobertura cochera', group: :extended, options: '["Cubierta", "Semicubierta", "Descubierta"]' },
	{ title: 'Cantidad de ascensores', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Cantidad de plantas', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Cantidad plantas', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Cantidad de naves', group: :extended, options: '{"type": "integer"}' },
	{ title: 'Categoría del edificio', group: :extended, options: '["Excelente", "Muy buena", "Buena", "Estándar", "Económica", "Precaria"]' },
	{ title: 'Jardín', group: :environments },
	{ title: 'Vestidor', group: :environments },
	{ title: 'Dormitorio en suite', group: :environments },
	{ title: 'Altillo', group: :environments },
	{ title: 'Dependencia servicio', group: :environments },
	{ title: 'Comedor', group: :environments },
	{ title: 'Toilette', group: :environments },
	{ title: 'Balcón', group: :environments },
	{ title: 'Cocina', group: :environments },
	{ title: 'Living', group: :environments },
	{ title: 'Comedor de diario', group: :environments },
	{ title: 'Lavadero', group: :environments },
	{ title: 'Patio', group: :environments },
	{ title: 'Hall', group: :environments },
	{ title: 'Baulera', group: :environments },
	{ title: 'Sótano', group: :environments },
	{ title: 'Escritorio', group: :environments },
	{ title: 'Living comedor', group: :environments },
	{ title: 'Terraza', group: :environments },
	{ title: 'Vigilancia', group: :general },
	{ title: 'Amoblado', group: :general },
	{ title: 'Parrilla', group: :general },
	{ title: 'Gimnasio', group: :general },
	{ title: 'Cancha deportes', group: :general },
	{ title: 'Laundry', group: :general },
	{ title: 'Hidromasaje', group: :general },
	{ title: 'Sauna', group: :general },
	{ title: 'Calefacción', group: :general },
	{ title: 'Solarium', group: :general },
	{ title: 'Quincho', group: :general },
	{ title: 'SUM', group: :general },
	{ title: 'Aire acondicionado', group: :general },
	{ title: 'Piscina', group: :general },
	{ title: 'Alarma', group: :general },
	{ title: 'Sala de juegos', group: :general }
	])